### PR TITLE
Decode HTML escape sequences inside server tags

### PR DESCRIPTION
**Pull request by WalkerMills**
Currently, using characters that are prettified by Earmark's smartypants
processing breaks templates since EEx cannot interpret those characters.
This includes single and double quotes, so string literals do not work
(string sigils work as long as they use a different delimiter).

Earmark still breaks EEx when `:smartypants` is set to `false` because
it HTML-encodes characters such as quotes inside server tags. I extended
`do_handle_smart_tags` to replace all HTML-encoded characters inside a
server tag instead of just the delimiters. I also added a new test +
fixture to exercise this functionality.

I bumped the patch version because this functionality already exists.
For example, you could not write `<%= String.upcase("foo") %>`, but you
could write `<%= String.upcase(~s/foo/) %>`. It is just broken for some
variants of Elixir syntax.

### CODE REVIEW

**Comment by boydm** [comment]
Thank you very much for this. It is a very good PR, so I'm going to take it right away. Will try to publish onto hex this week.

**Comment by WalkerMills** [comment]
Awesome, thanks for the fast turnaround!

**Comment by boydm** [comment]
While my attention was on it, just published 1.0.2 to hex.
Thank you so much for the contribution!

**Comment by WalkerMills** [comment]
Haha well while my attention is on it, I think I'm going to fix issue #8. It looks like the solution is similar, but with percent encoding. Should have thought of this before deleting my fork lol.

**Comment by WalkerMills** [comment]
PR #10 is up; let me know if I need to bump the patch version.

**Pull request merged**
